import type { StageId } from "@/types/schema"

export type UiLocale = "ko" | "en"

export const DEFAULT_UI_LOCALE: UiLocale = "ko"

export const UI_LOCALE_OPTIONS: Array<{
  value: UiLocale
  label: string
  shortLabel: string
}> = [
  { value: "ko", label: "한국어", shortLabel: "KO" },
  { value: "en", label: "English", shortLabel: "EN" },
]

export function resolveUiLocale(value: unknown): UiLocale | null {
  return value === "ko" || value === "en" ? value : null
}

const stageNames: Record<StageId, { ko: string; en: string }> = {
  "PRE.1": { ko: "EPUB 원문 변환", en: "EPUB to RawChapter JSON" },
  "PRE.2": { ko: "콘텐츠 분류", en: "Content Classification" },
  "ENT.1": { ko: "멘션 추출", en: "Mention Extraction" },
  "ENT.2": { ko: "멘션 검증", en: "Mention Validation" },
  "ENT.3": { ko: "엔티티 해소", en: "Entity Resolution" },
  "STATE.1": { ko: "상태 추적", en: "State Tracking" },
  "STATE.2": { ko: "상태 검증", en: "State Validation" },
  "STATE.3": { ko: "경계 탐지", en: "Boundary Detection" },
  "SCENE.1": { ko: "장면 패킷 생성", en: "Scene Packet Builder" },
  "SCENE.2": { ko: "장면 인덱스 추출", en: "Scene Index Extraction" },
  "SCENE.3": { ko: "장면 검증", en: "Scene Validation" },
  "VIS.1": { ko: "시각 의미 정제", en: "Semantic Clarification" },
  "VIS.2": { ko: "무대 청사진", en: "Stage Blueprint" },
  "VIS.3": { ko: "렌더 패키지", en: "Render Package" },
  "VIS.4": { ko: "이미지 생성", en: "Image Generation" },
  "SUB.1": { ko: "하위 장면 후보", en: "Subscene Proposal" },
  "SUB.2": { ko: "하위 장면 상태", en: "Subscene State" },
  "SUB.3": { ko: "하위 장면 검증", en: "Subscene Validation" },
  "SUB.4": { ko: "개입 패키징", en: "Intervention Packaging" },
  "SUP.0": { ko: "지원 메모리", en: "Support Memory" },
  "SUP.1": { ko: "공통 지원 맥락", en: "Shared Support Context" },
  "SUP.2": { ko: "현재 상태와 경계 변화", en: "Snapshot and Boundary" },
  "SUP.3": { ko: "인과 연결", en: "Causal Bridges" },
  "SUP.4": { ko: "인물과 관계", en: "Character and Relation" },
  "SUP.5": { ko: "복귀와 지시어", en: "Reentry and Reference" },
  "SUP.6": { ko: "지원 노출 정책", en: "Support Policy" },
  "SUP.7": { ko: "리더 지원 패키지", en: "Reader Support Package" },
  "FINAL.1": { ko: "장면 리더 패키지", en: "Scene Reader Package" },
  "FINAL.2": { ko: "오버레이 정제", en: "Overlay Refinement" },
}

function localizedStageNames(locale: UiLocale): Record<StageId, string> {
  return Object.fromEntries(
    Object.entries(stageNames).map(([stageId, names]) => [stageId, names[locale]]),
  ) as Record<StageId, string>
}

export const UI_STRINGS = {
  ko: {
    language: {
      label: "언어",
      selectLabel: "UI 언어 선택",
    },
    theme: {
      label: "테마",
      selectLabel: "화면 테마 선택",
      options: {
        system: "기기",
        light: "라이트",
        dark: "다크",
      },
    },
    app: {
      title: "Story Visualization",
      noDocument: "먼저 EPUB을 업로드하거나 기존 문서를 선택하세요.",
    },
    nav: {
      upload: "업로드",
      pipeline: "파이프라인",
      graph: "그래프",
      reader: "리더",
      legacy: "이전 데이터",
    },
    common: {
      chapter: "챕터",
      previous: "이전",
      next: "다음",
      current: "현재",
      loading: "로딩 중...",
      refresh: "새로고침",
      open: "열기",
      close: "닫기",
      search: "검색",
      delete: "삭제",
      deleting: "삭제 중...",
      new: "새로 만들기",
      draft: "초안",
      favorite: "즐겨찾기",
      favoriteActive: "* 즐겨찾기",
      readOnly: "읽기 전용",
      result: "결과",
      body: "본문",
      prompt: "프롬프트",
      response: "응답",
      evidence: "근거",
      source: "출처",
      legend: "범례",
      scenes: "장면",
      events: "사건",
      edges: "엣지",
      nodes: "노드",
      modelUnknown: "모델 알 수 없음",
    },
    upload: {
      parsing: "EPUB 분석 중...",
      drop: "EPUB 파일을 여기에 놓으세요",
      browse: "또는 클릭해서 파일 선택",
      uploadFailed: "업로드에 실패했습니다.",
    },
    documents: {
      title: "기존 파일",
      description: "이전에 업로드한 문서를 선택해 저장된 챕터에서 이어서 작업합니다.",
      empty: "아직 업로드된 문서가 없습니다.",
      loading: "저장된 문서를 불러오는 중...",
      loadFailed: "문서를 불러오지 못했습니다.",
      loadChaptersFailed: "챕터를 불러오지 못했습니다.",
    },
    pipeline: {
      runId: "Run ID",
      savedRuns: "저장된 실행",
      currentDraft: "현재 초안 또는 직접 입력한 run",
      loadingSavedResults: "저장된 결과를 불러오는 중...",
      noSavedRun: "저장된 run 없음",
      selectSavedRun: "저장된 run 선택",
      favoriteTitle: "이 저장된 run의 즐겨찾기 여부를 바꿉니다.",
      favoriteDisabledTitle: "먼저 run을 저장해야 즐겨찾기로 지정할 수 있습니다.",
      deleteConfirm: "Run {runId}을 삭제할까요? 이 run에 저장된 모든 단계 결과가 제거됩니다.",
      runAll: "전체 단계 실행",
      runRemaining: "남은 단계 실행",
      runRemainingTitleNone: "현재 run에 남은 단계가 없습니다.",
      runRemainingTitleSome: "저장 결과가 없는 단계만 실행합니다.",
      refreshResults: "결과 새로고침",
      runLabel: "run",
      stages: "단계",
      runStage: "실행",
      pending: "대기",
      noSavedStageResult: "이 단계에 저장된 결과가 없습니다.",
      latestOnlyDelete: "가장 최근에 저장된 단계만 삭제할 수 있습니다. 현재 최신 단계: {stageId}",
      deleteStageResult: "현재 run에서 이 단계 결과를 삭제합니다.",
      stageSlotPending: "단계 슬롯은 추가되어 있지만 아직 구현이 연결되지 않았습니다.",
      savedResult: "현재 run에 저장된 결과입니다.",
      noStageResult: "현재 run에 아직 이 단계 결과가 없습니다.",
      viewReader: "리더 화면 보기",
      viewGraph: "지식 그래프 보기",
      graphTitle: "Pipeline Graph",
      graphDescription: "브랜치 구조에서 단계를 선택하거나 실행합니다. SUP는 FINAL.1로 이어지는 독자 지원 브랜치입니다.",
      saved: "저장됨",
      running: "실행 중",
      error: "오류",
      from: "입력",
      llmDebug: "LLM 프롬프트 / 응답",
      openLarge: "크게 보기",
      noPrompt: "저장된 프롬프트가 없습니다.",
      noResponse: "저장된 응답이 없습니다.",
      trial: "시도",
      noTextGenerated: "생성된 텍스트가 없습니다.",
    },
    graphPage: {
      eyebrow: "그래프 제어",
      title: "현재 run 그래프 조회",
      description: "`documents_v2`에 저장된 graph projection을 조회합니다. 기존 `documents` 데이터는 이전 데이터 탭에서 확인합니다.",
      noRunSelected: "지식 그래프를 조회하려면 저장된 run을 선택하거나 생성하세요.",
    },
    legacy: {
      documentsTitle: "이전 문서",
      documentsDescription: "기존 documents 컬렉션에 남아 있는 이전 실행 결과를 읽기 전용으로 확인합니다.",
      documentsEmpty: "기존 documents 컬렉션에서 문서를 찾지 못했습니다.",
      readerTitle: "이전 리더",
      readerDescription: "새 실행은 documents_v2에 저장되고, 이 화면은 기존 documents 컬렉션을 수정하지 않습니다.",
      selectDocument: "왼쪽에서 이전 문서를 선택하세요.",
      runLabel: "이전 Run",
    },
    readerPage: {
      loading: "리더 데이터를 불러오는 중...",
      noSavedRuns: "이 챕터에 저장된 run이 없습니다.",
      noResult: "결과가 없습니다. 먼저 파이프라인을 실행하세요.",
    },
    bookMemory: {
      eyebrow: "책 메모리",
      title: "크로스 챕터 메모리 스냅샷",
      description: "챕터별로 서로 다른 run 결과를 조합해 책 단위 메모리를 만듭니다. 아래에서 각 챕터에 사용할 run을 고른 뒤, SUP.0이 있는 조합으로 빌드합니다.",
      build: "선택한 run으로 빌드",
      building: "빌드 중...",
      loadLatest: "최신 스냅샷 불러오기",
      chapterRunSelection: "챕터별 run 선택",
      manualReady: "수동 {manual}/{total}, SUP.0 준비 {ready}/{total}",
      checking: " 확인 중...",
      loadingRunOptions: "run 옵션을 불러오는 중...",
      noSavedRun: "저장된 run 없음",
      autoSelect: "SUP.0이 있는 run 자동 선택",
      current: "현재",
      auto: "자동",
      bookRun: "책 Run",
      chapters: "챕터",
      scenes: "장면",
      edges: "엣지",
      entityThreads: "엔티티 스레드",
      missingChapters: "누락된 챕터",
      crossChapterEdges: "크로스 챕터 엣지",
      noEdges: "아직 크로스 챕터 엣지가 없습니다.",
      noThreads: "아직 반복 엔티티 스레드가 없습니다.",
      noSnapshot: "아직 책 메모리 스냅샷이 없습니다. 최소 한 챕터에 SUP.0이 준비된 뒤 빌드하세요.",
      readyStatus: {
        ok: "준비됨",
        missing: "없음",
        unknown: "확인 전",
      },
    },
    graphExplorer: {
      eyebrow: "지식 그래프",
      title: "조회 가능한 그래프 projection",
      description: "SUP.0/ENT.3 산출물을 node와 edge로 투영해 현재 run 기준으로 검색하고, 선택한 node 주변 hop을 확인합니다.",
      allNodes: "전체 노드",
      scenes: "장면",
      events: "사건",
      characters: "인물",
      places: "장소",
      entities: "엔티티",
      mentions: "멘션",
      rebuild: "Projection 재빌드",
      rebuilding: "재빌드 중...",
      projected: "{nodes}개 node와 {edges}개 edge를 {stages}에서 projection했습니다.",
      noGraphStages: "그래프 단계 없음",
      placeholder: "인물, 장소, 장면, 사건 검색...",
      noProjection: "Graph projection이 없습니다. ENT.3/SUP.0을 실행했거나 해당 단계가 존재한다면 Projection 재빌드를 누르세요.",
      nodeList: "노드",
      edges: "엣지",
      neighborhood: "주변 노드",
      clearFocus: "포커스 해제",
      evidenceRefs: "근거 참조",
      noEdges: "현재 쿼리에 해당하는 edge가 없습니다.",
      nodeSummary: {
        scene: "장면",
        event: "사건",
        entity: "엔티티",
      },
    },
    reader: {
      noScenes: "사용 가능한 장면이 없습니다.",
      scene: "장면",
      showSummary: "요약 보기",
      hideSummary: "요약 숨기기",
      subscene: "하위 장면",
      moreSupport: "추가 읽기 지원",
      blueprintAvailable: "청사진 사용 가능",
      noImage: "이미지 없음",
      visualMinimized: "시각 지원 최소화",
      visualScore: "점수",
      visualMinimizedMessage: "이미지는 준비되어 있지만, 현재 장면은 시각 정보보다 텍스트/인과 지원이 더 필요해 보입니다. 공간 맥락이 필요할 때만 열어보세요.",
      noVisual: "이 장면에는 사용할 수 있는 시각 지원이 없습니다.",
      sceneFocusDetails: "장면 초점 세부 정보",
      subsceneView: "하위 장면 보기",
      characterView: "인물 보기",
      pairView: "관계 보기",
      castPlaceVisualCues: "인물 / 장소 / 시각 단서",
      supportPriority: "우선순위",
      supportKind: {
        snapshot: "지금",
        boundary_delta: "변화",
        causal_bridge: "이유",
        character_focus: "인물",
        relation_delta: "관계",
        reentry_recap: "복귀",
        reference_repair: "지시어",
        spatial_continuity: "장소",
        visual_context: "단서",
      },
      panelButton: {
        goal: "목표",
        problem: "문제",
        what_changed: "변화",
        why_it_matters: "의미",
        object: "대상",
        action: "행동",
        event: "사건",
      },
      fallback: {
        readerSupport: "읽기 지원",
        noSubscene: "하위 장면 지원이 없습니다.",
        selectedPair: "선택한 관계",
        relationView: "관계 보기",
        noPairHint: "이 조합에 맞는 관계 힌트가 준비되지 않았습니다.",
        subsceneOverview: "하위 장면 개요",
      },
      memory: {
        eyebrow: "크로스 챕터 메모리",
        missing: "크로스 챕터 메모리가 아직 로드되지 않았습니다. Graph 탭에서 BOOK.0을 만든 뒤 다시 확인하세요.",
        runMismatch: "현재 Reader run과 BOOK.0에 사용된 run이 다릅니다. BOOK.0 run: {runId}",
        bridges: "연결",
        threads: "스레드",
        path: "경로",
        incoming: "이전 연결",
        outgoing: "다음 연결",
        from: "from",
        to: "to",
        noBridge: "이 scene과 직접 연결된 cross-chapter edge가 아직 없습니다.",
        noThread: "현재 챕터와 연결된 반복 entity thread가 없습니다.",
        noPath: "현재 scene을 BOOK.0 scene path에서 찾지 못했습니다.",
        chaptersShort: "ch",
        mentions: "mentions",
        reappearsHere: "이 장면에서 다시 등장",
        edgeLabel: {
          chapter_sequence: "순서",
          cross_chapter_character_thread: "인물 스레드",
          cross_chapter_same_place: "같은 장소",
          cross_chapter_place_shift: "장소 전환",
          cross_chapter_causal_bridge: "인과 연결",
          entity_reappearance: "재등장",
        },
      },
    },
    stageNames: localizedStageNames("ko"),
  },
  en: {
    language: {
      label: "Language",
      selectLabel: "Select UI language",
    },
    theme: {
      label: "Theme",
      selectLabel: "Select color theme",
      options: {
        system: "System",
        light: "Light",
        dark: "Dark",
      },
    },
    app: {
      title: "Story Visualization",
      noDocument: "Upload an EPUB or select an existing document first.",
    },
    nav: {
      upload: "Upload",
      pipeline: "Pipeline",
      graph: "Graph",
      reader: "Reader",
      legacy: "Legacy",
    },
    common: {
      chapter: "Chapter",
      previous: "Prev",
      next: "Next",
      current: "current",
      loading: "Loading...",
      refresh: "Refresh",
      open: "Open",
      close: "Close",
      search: "Search",
      delete: "Delete",
      deleting: "Deleting...",
      new: "New",
      draft: "Draft",
      favorite: "Favorite",
      favoriteActive: "* Favorite",
      readOnly: "read-only",
      result: "Result",
      body: "Body",
      prompt: "Prompt",
      response: "Response",
      evidence: "evidence",
      source: "Source",
      legend: "Legend",
      scenes: "Scenes",
      events: "Events",
      edges: "Edges",
      nodes: "Nodes",
      modelUnknown: "model unknown",
    },
    upload: {
      parsing: "Parsing EPUB...",
      drop: "Drop an EPUB file here",
      browse: "or click to browse",
      uploadFailed: "Upload failed",
    },
    documents: {
      title: "Existing Files",
      description: "Pick a previously uploaded document and continue from its saved chapters.",
      empty: "No uploaded documents found yet.",
      loading: "Loading saved documents...",
      loadFailed: "Failed to load documents",
      loadChaptersFailed: "Failed to load chapters",
    },
    pipeline: {
      runId: "Run ID",
      savedRuns: "Saved Runs",
      currentDraft: "Current draft or custom run",
      loadingSavedResults: "loading saved results...",
      noSavedRun: "No saved run",
      selectSavedRun: "Select a saved run",
      favoriteTitle: "Toggle favorite for this saved run",
      favoriteDisabledTitle: "Save a run first to favorite it",
      deleteConfirm: "Delete run {runId}? This removes all saved stage results in this run.",
      runAll: "Run All Stages",
      runRemaining: "Run Remaining Stages",
      runRemainingTitleNone: "No remaining stages in the current run.",
      runRemainingTitleSome: "Run only stages without saved results.",
      refreshResults: "Refresh Results",
      runLabel: "run",
      stages: "Stages",
      runStage: "Run",
      pending: "Pending",
      noSavedStageResult: "No saved result for this stage.",
      latestOnlyDelete: "Only the latest saved stage can be deleted. Current latest: {stageId}",
      deleteStageResult: "Delete this stage result from the current run.",
      stageSlotPending: "Stage slot is added to the project structure, but implementation is not wired yet.",
      savedResult: "Saved result for current run.",
      noStageResult: "No result for this stage in the current run yet.",
      viewReader: "View reader screen",
      viewGraph: "View knowledge graph",
      graphTitle: "Pipeline Graph",
      graphDescription: "Select or run stages by branch. SUP is the reader-support branch feeding FINAL.1.",
      saved: "saved",
      running: "running",
      error: "error",
      from: "from",
      llmDebug: "LLM Prompt / Response",
      openLarge: "Open Large",
      noPrompt: "No prompt saved.",
      noResponse: "No response saved.",
      trial: "Trial",
      noTextGenerated: "No text generated.",
    },
    graphPage: {
      eyebrow: "Graph Controls",
      title: "Current run graph query",
      description: "Query the graph projection saved under `documents_v2`. Existing `documents` data is available in the legacy tab.",
      noRunSelected: "Select or create a saved run before querying the knowledge graph.",
    },
    legacy: {
      documentsTitle: "Legacy Documents",
      documentsDescription: "Read old execution results left in the existing documents collection.",
      documentsEmpty: "No documents were found in the existing documents collection.",
      readerTitle: "Legacy Reader",
      readerDescription: "New executions are saved to documents_v2; this screen does not modify the existing documents collection.",
      selectDocument: "Select a legacy document on the left.",
      runLabel: "Legacy Run",
    },
    readerPage: {
      loading: "Loading reader data...",
      noSavedRuns: "No saved runs for this chapter.",
      noResult: "No result is available. Run the pipeline first.",
    },
    bookMemory: {
      eyebrow: "Book Memory",
      title: "Cross-chapter memory snapshot",
      description: "Book-level memory combines different run outputs per chapter. Choose the run to use for each chapter below, then build from runs that have SUP.0.",
      build: "Build from Selected Runs",
      building: "Building...",
      loadLatest: "Load Latest",
      chapterRunSelection: "Chapter run selection",
      manualReady: "manual {manual}/{total}, SUP.0 ready {ready}/{total}",
      checking: " checking...",
      loadingRunOptions: "Loading run options...",
      noSavedRun: "No saved run",
      autoSelect: "Auto select SUP.0-ready run",
      current: "current",
      auto: "auto",
      bookRun: "Book Run",
      chapters: "Chapters",
      scenes: "Scenes",
      edges: "Edges",
      entityThreads: "Entity Threads",
      missingChapters: "Missing chapters",
      crossChapterEdges: "Cross-chapter edges",
      noEdges: "No cross-chapter edges yet.",
      noThreads: "No repeated entity thread yet.",
      noSnapshot: "No book memory snapshot yet. Build one after SUP.0 is available for at least one chapter.",
      readyStatus: {
        ok: "ok",
        missing: "missing",
        unknown: "unknown",
      },
    },
    graphExplorer: {
      eyebrow: "Knowledge Graph",
      title: "Queryable graph projection",
      description: "Project SUP.0/ENT.3 artifacts into nodes and edges, search the current run, and inspect the selected node neighborhood.",
      allNodes: "All nodes",
      scenes: "Scenes",
      events: "Events",
      characters: "Characters",
      places: "Places",
      entities: "Entities",
      mentions: "Mentions",
      rebuild: "Rebuild Projection",
      rebuilding: "Rebuilding...",
      projected: "Projected {nodes} nodes and {edges} edges from {stages}.",
      noGraphStages: "no graph stages",
      placeholder: "Search character, place, scene, event...",
      noProjection: "No graph projection found. Run ENT.3/SUP.0 or click Rebuild Projection after those stages exist.",
      nodeList: "Nodes",
      edges: "Edges",
      neighborhood: "Neighborhood",
      clearFocus: "Clear Focus",
      evidenceRefs: "evidence refs",
      noEdges: "No edges for the current query.",
      nodeSummary: {
        scene: "scene",
        event: "event",
        entity: "entity",
      },
    },
    reader: {
      noScenes: "No scenes available.",
      scene: "Scene",
      showSummary: "Show Summary",
      hideSummary: "Hide Summary",
      subscene: "Subscene",
      moreSupport: "More reading support",
      blueprintAvailable: "Blueprint available",
      noImage: "No image",
      visualMinimized: "Visual support minimized",
      visualScore: "score",
      visualMinimizedMessage: "The image is available, but the current scene appears to need text/causal support more than visual support. Open it only if spatial context would help.",
      noVisual: "No visual support is available for this scene.",
      sceneFocusDetails: "Scene focus details",
      subsceneView: "Subscene View",
      characterView: "Character View",
      pairView: "Pair View",
      castPlaceVisualCues: "Cast / place / visual cues",
      supportPriority: "priority",
      supportKind: {
        snapshot: "Now",
        boundary_delta: "Shift",
        causal_bridge: "Why",
        character_focus: "Cast",
        relation_delta: "Relation",
        reentry_recap: "Resume",
        reference_repair: "Names",
        spatial_continuity: "Place",
        visual_context: "Cues",
      },
      panelButton: {
        goal: "Goal",
        problem: "Problem",
        what_changed: "Change",
        why_it_matters: "Impact",
        object: "Object",
        action: "Action",
        event: "Event",
      },
      fallback: {
        readerSupport: "Reader support",
        noSubscene: "No subscene support available.",
        selectedPair: "Selected pair",
        relationView: "Relation view",
        noPairHint: "No pair-specific hint was prepared for this combination.",
        subsceneOverview: "Subscene overview",
      },
      memory: {
        eyebrow: "Cross-chapter Memory",
        missing: "Cross-chapter memory is not loaded yet. Build BOOK.0 in the Graph tab, then check again.",
        runMismatch: "The current Reader run differs from the run used by BOOK.0. BOOK.0 run: {runId}",
        bridges: "Bridges",
        threads: "Threads",
        path: "Path",
        incoming: "incoming",
        outgoing: "outgoing",
        from: "from",
        to: "to",
        noBridge: "No cross-chapter edge is directly connected to this scene yet.",
        noThread: "No repeated entity thread is connected to the current chapter.",
        noPath: "The current scene was not found in the BOOK.0 scene path.",
        chaptersShort: "ch",
        mentions: "mentions",
        reappearsHere: "reappears in this scene",
        edgeLabel: {
          chapter_sequence: "Sequence",
          cross_chapter_character_thread: "Cast thread",
          cross_chapter_same_place: "Same place",
          cross_chapter_place_shift: "Place shift",
          cross_chapter_causal_bridge: "Causal bridge",
          entity_reappearance: "Reappearance",
        },
      },
    },
    stageNames: localizedStageNames("en"),
  },
} as const

export type UiStrings = (typeof UI_STRINGS)[UiLocale]
