import type { StageId } from "@/types/schema"

export const GEMINI_FLASH_MODEL = "google/gemini-3.5-flash"
export const PRE2_MODEL = "openai/gpt-4o-mini"
export const ENT2_MODEL = "google/gemini-3.1-pro-preview"

export const DEFAULT_STAGE_MODELS: Partial<Record<StageId, string>> = {
  "PRE.2": PRE2_MODEL,
  "EVID.1A": GEMINI_FLASH_MODEL,
  "EVID.1B": GEMINI_FLASH_MODEL,
  "EVID.1C": GEMINI_FLASH_MODEL,
  "EVID.1D": GEMINI_FLASH_MODEL,
  "EVID.2": GEMINI_FLASH_MODEL,
  "EVID.3": GEMINI_FLASH_MODEL,
  "EVENT.1": GEMINI_FLASH_MODEL,
  "SCENE.0": GEMINI_FLASH_MODEL,
  "ENT.1": GEMINI_FLASH_MODEL,
  "ENT.2": ENT2_MODEL,
  "ENT.3": GEMINI_FLASH_MODEL,
  "STATE.2": GEMINI_FLASH_MODEL,
  "STATE.3": GEMINI_FLASH_MODEL,
  "SCENE.2": GEMINI_FLASH_MODEL,
  "SCENE.3": GEMINI_FLASH_MODEL,
  "VIS.1": GEMINI_FLASH_MODEL,
  "VIS.2": GEMINI_FLASH_MODEL,
  "VIS.4": GEMINI_FLASH_MODEL,
  "SUB.1": GEMINI_FLASH_MODEL,
  "SUB.2": GEMINI_FLASH_MODEL,
  "SUB.3": GEMINI_FLASH_MODEL,
  "SUB.4": GEMINI_FLASH_MODEL,
  "FINAL.2": GEMINI_FLASH_MODEL,
}
